# Generated by Django 5.2.6 on 2025-09-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_test_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='my_test_test',
        ),
    ]
