"""
Django settings for HelloDjango project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$p_d72by%%7$%7h1ka!r$oaobxsxw-6wt45w@$mmb71cptt1qq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',  # 添加验证码应用
    'my_test',
    'happy'
]

# 验证码设置
CAPTCHA_IMAGE_SIZE = (120, 50)  # 验证码图片尺寸
CAPTCHA_LENGTH = 4  # 验证码字符数
CAPTCHA_TIMEOUT = 5  # 验证码有效期(分钟)

# 允许无需登录的路径
LOGIN_EXEMPT_URLS = [
    r'^captcha/',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # 增强网站安全性，提供 HTTP 安全相关的头部设置
    'django.contrib.sessions.middleware.SessionMiddleware', # 管理会话（Session）功能
    'django.middleware.common.CommonMiddleware', # 处理通用 HTTP 请求/响应逻辑
    'django.middleware.csrf.CsrfViewMiddleware', # 防止跨站请求伪造（CSRF）攻击
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 处理用户认证，为请求添加 request.user对象
    'django.contrib.messages.middleware.MessageMiddleware', # 管理一次性消息（如操作成功提示）
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # 防止点击劫持（Clickjacking）攻击
    'happy.middleware.AuthCheckMiddleware',  # 自定义登录检查
    'happy.middleware.LoggingMiddleware',    # 自定义日志记录
    'happy.middleware.ErrorHandlerMiddleware',  # 自定义异常处理
]

ROOT_URLCONF = 'HelloDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HelloDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = { 
    'default': 
    { 
        'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
        'NAME': 'monica', # 数据库名称
        'HOST': '127.0.0.1', # 数据库地址，本机 ip 地址 127.0.0.1 
        'PORT': 3306, # 端口 
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'mm0311', # 数据库密码
        'OPTIONS': {
            'charset': 'utf8',
        }
    }  
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-hans'  # 改为中文
TIME_ZONE = 'Asia/Shanghai'  # 改为中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_DIRS = [ 
    os.path.join(BASE_DIR, "statics"), 
]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',  
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
