# Generated by Django 5.2.6 on 2025-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=100, verbose_name='调用者')),
                ('status', models.SmallIntegerField(choices=[(1, '成功'), (0, '失败')], verbose_name='状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.FloatField(verbose_name='耗时(秒)')),
                ('record_count', models.IntegerField(verbose_name='记录数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'API日志',
                'verbose_name_plural': 'API日志',
                'db_table': 'api_log',
                'indexes': [models.Index(fields=['caller', 'start_time'], name='api_log_caller_856e93_idx')],
            },
        ),
    ]
