# Generated by Django 5.2.6 on 2025-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(max_length=50, verbose_name='工艺编码')),
                ('process_name', models.CharField(max_length=100, verbose_name='工艺名称')),
                ('process_version', models.CharField(max_length=20, verbose_name='工艺版本')),
                ('parameters', models.TextField(blank=True, null=True, verbose_name='工艺参数')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='温度(℃)')),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='压力(MPa)')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='速度(m/min)')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作员')),
                ('execute_time', models.DateTimeField(verbose_name='执行时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工艺数据',
                'verbose_name_plural': '工艺数据',
                'db_table': 'process_data',
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号')),
                ('production_date', models.DateTimeField(verbose_name='生产日期')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('quantity', models.IntegerField(verbose_name='生产数量')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作员')),
                ('equipment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备编号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生产数据',
                'verbose_name_plural': '生产数据',
                'db_table': 'production_data',
            },
        ),
    ]
